/**
 * SimPool: runs AI-vs-AI matches in parallel Web Workers, falling back to the calling thread when workers
 * are unavailable (no `Worker`, blob: URLs blocked by CSP, old WebViews) or fail to boot.
 *
 * Bundling notes
 * --------------
 * The worker code is embedded as a string (`WORKER_SOURCE`, generated by `scripts/build-worker.mjs` into
 * `./worker.bundle.ts`) and started from a Blob URL, so the app still ships as ONE file: no separate worker
 * script is fetched at runtime and file:// / single-HTML builds work. Because the bundle is a plain `.ts`
 * module exporting a string, neither Vite nor esbuild need extra configuration. If you would rather keep
 * the artifact as `worker.bundle.txt`, import it here instead and add `--loader:.txt=text` to the esbuild
 * command (plus `?raw` for Vite and a `declare module "*.txt"` d.ts).
 * Run `pnpm --filter viewer build:worker` after touching anything the worker imports (engine, protocol.ts).
 */
import { TUNING } from "@3sec/engine";
import { simulateInThread, type MatchResult, type SimJob, type WorkerRequest, type WorkerResponse } from "./protocol";
import { WORKER_SOURCE } from "./worker.bundle";

export type { MatchResult, ResultPlayer, SimJob } from "./protocol";
export { simulateInThread } from "./protocol";

export type SimMode = "workers" | "in-thread";
export type SimProgress = (done: number, total: number, last: MatchResult) => void;

export interface SimPoolOptions {
  /** Number of workers (default: min(hardwareConcurrency ?? 2, 4)). */
  size?: number;
  /** How long to wait for a worker's "ready" message before giving up on workers (default 4000 ms). */
  bootTimeoutMs?: number;
  /** Skip workers entirely (tests, debugging). */
  forceInThread?: boolean;
}

interface Slot {
  worker: Worker;
}

export const defaultPoolSize = (): number => {
  const hc = typeof navigator !== "undefined" ? navigator.hardwareConcurrency : undefined;
  return Math.max(1, Math.min(hc || 2, 4));
};

const yieldToUi = (): Promise<void> => new Promise((r) => setTimeout(r, 0));

export class SimPool {
  readonly size: number;
  private slots: Slot[] = [];
  private boot: Promise<void> | null = null;
  private chain: Promise<unknown> = Promise.resolve();
  private disposed = false;
  private modeValue: SimMode | null = null;

  constructor(private readonly options: SimPoolOptions = {}) {
    this.size = Math.max(1, options.size ?? defaultPoolSize());
  }

  /** Whether this runtime can start Blob URL workers at all (booting may still fail; see `mode`). */
  static get workersSupported(): boolean {
    return typeof Worker === "function" && typeof Blob === "function" && typeof URL !== "undefined" && typeof URL.createObjectURL === "function";
  }

  /** "workers" or "in-thread" once booted (after the first `run`), null before. */
  get mode(): SimMode | null {
    return this.modeValue;
  }

  /** Live worker count (0 in in-thread mode). */
  get workerCount(): number {
    return this.slots.length;
  }

  /**
   * Simulate every job to full time. Resolves with results keyed by job id, in whatever order they finished.
   * Calls are serialized: a second `run` waits for the first. Rejects if a match itself throws.
   */
  run(jobs: readonly SimJob[], onProgress?: SimProgress): Promise<Map<string, MatchResult>> {
    const p = this.chain.then(() => this.runExclusive(jobs, onProgress));
    this.chain = p.catch(() => undefined);
    return p;
  }

  /** Terminate the workers. The pool cannot be reused afterwards. */
  dispose(): void {
    this.disposed = true;
    for (const s of this.slots) s.worker.terminate();
    this.slots = [];
  }

  // ------------------------------------------------------------------ boot

  private ensureBooted(): Promise<void> {
    if (!this.boot) this.boot = this.spawn();
    return this.boot;
  }

  private async spawn(): Promise<void> {
    if (this.options.forceInThread || !SimPool.workersSupported) {
      this.modeValue = "in-thread";
      return;
    }
    let url: string;
    try {
      url = URL.createObjectURL(new Blob([WORKER_SOURCE], { type: "text/javascript" }));
    } catch {
      this.modeValue = "in-thread";
      return;
    }
    try {
      const workers = await Promise.all(Array.from({ length: this.size }, () => this.bootOne(url)));
      this.slots = workers.filter((w): w is Worker => w !== null).map((worker) => ({ worker }));
    } finally {
      URL.revokeObjectURL(url);
    }
    if (this.disposed) this.dispose();
    this.modeValue = this.slots.length ? "workers" : "in-thread";
  }

  private bootOne(url: string): Promise<Worker | null> {
    return new Promise((resolve) => {
      let w: Worker;
      try {
        w = new Worker(url);
      } catch {
        resolve(null);
        return;
      }
      const cleanup = () => {
        clearTimeout(timer);
        w.removeEventListener("message", onMessage);
        w.removeEventListener("error", onError);
      };
      const fail = () => {
        cleanup();
        try { w.terminate(); } catch { /* ignore */ }
        resolve(null);
      };
      const onMessage = (e: MessageEvent<WorkerResponse>) => {
        if (e.data?.kind === "ready") {
          cleanup();
          resolve(w);
        }
      };
      const onError = () => fail();
      const timer = setTimeout(fail, this.options.bootTimeoutMs ?? 4000);
      w.addEventListener("message", onMessage);
      w.addEventListener("error", onError);
    });
  }

  // ------------------------------------------------------------------ run

  private async runExclusive(jobs: readonly SimJob[], onProgress?: SimProgress): Promise<Map<string, MatchResult>> {
    if (this.disposed) throw new Error("SimPool disposed");
    await this.ensureBooted();
    // Workers have their own copy of the engine's mutable TUNING; ship the main thread's values so results match in-thread runs.
    const tuning = { ...TUNING };
    const queue: SimJob[] = jobs.map((j) => (j.tuning ? j : { ...j, tuning }));
    const results = new Map<string, MatchResult>();
    const total = jobs.length;
    let done = 0;
    const report = (r: MatchResult) => {
      results.set(r.id, r);
      done++;
      onProgress?.(done, total, r);
    };
    if (this.slots.length) await Promise.all(this.slots.map((slot) => this.workerLoop(slot, queue, report)));
    // Anything still queued (no workers, or all of them died) runs here, yielding between matches so the UI can paint.
    while (queue.length) {
      report(simulateInThread(queue.shift()!));
      if (queue.length) await yieldToUi();
    }
    return results;
  }

  private async workerLoop(slot: Slot, queue: SimJob[], report: (r: MatchResult) => void): Promise<void> {
    while (queue.length && this.slots.includes(slot)) {
      const job = queue.shift()!;
      try {
        report(await this.dispatch(slot, job));
      } catch (err) {
        if (err instanceof SimError) throw err; // the match itself failed; it would fail in-thread too
        // The worker crashed (OOM, script error): retire it and put the job back for someone else.
        this.retire(slot);
        queue.unshift(job);
        if (typeof console !== "undefined") console.warn("[SimPool] worker failed, retiring it", err);
        return;
      }
    }
  }

  private dispatch(slot: Slot, job: SimJob): Promise<MatchResult> {
    return new Promise((resolve, reject) => {
      const w = slot.worker;
      const cleanup = () => {
        w.removeEventListener("message", onMessage);
        w.removeEventListener("error", onError);
      };
      const onMessage = (e: MessageEvent<WorkerResponse>) => {
        const m = e.data;
        if (!m || !("id" in m) || m.id !== job.id) return;
        cleanup();
        if (m.kind === "done") resolve(m.result);
        else reject(new SimError(job.id, m.message));
      };
      const onError = (e: ErrorEvent) => {
        cleanup();
        reject(e.error ?? new Error(e.message || "worker error"));
      };
      w.addEventListener("message", onMessage);
      w.addEventListener("error", onError);
      const msg: WorkerRequest = { kind: "run", job };
      w.postMessage(msg);
    });
  }

  private retire(slot: Slot): void {
    this.slots = this.slots.filter((s) => s !== slot);
    try { slot.worker.terminate(); } catch { /* ignore */ }
    if (!this.slots.length) this.modeValue = "in-thread";
  }
}

/** A match threw inside the worker (engine error); carries the worker-side message/stack. */
export class SimError extends Error {
  constructor(readonly jobId: string, message: string) {
    super(`match ${jobId} failed: ${message}`);
    this.name = "SimError";
  }
}

let shared: SimPool | null = null;
/** App-wide lazily created pool; workers boot on the first `run`. */
export function getSimPool(): SimPool {
  return (shared ??= new SimPool());
}
