// Bundles src/sim/worker-entry.ts (IIFE, minified) and writes it as a string module, src/sim/worker.bundle.ts,
// so the worker can be started from a Blob URL inside a single-file app bundle. Run: pnpm --filter viewer build:worker
import { createRequire } from "node:module";
import { writeFileSync, readFileSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
export const viewerDir = resolve(here, "..");
const entry = resolve(viewerDir, "src/sim/worker-entry.ts");
const outFile = resolve(viewerDir, "src/sim/worker.bundle.ts");

/** esbuild is not a direct dependency of the viewer; borrow the copy vite depends on. */
export async function loadEsbuild() {
  const require = createRequire(import.meta.url);
  let path;
  try {
    path = require.resolve("esbuild");
  } catch {
    path = createRequire(require.resolve("vite/package.json")).resolve("esbuild");
  }
  const mod = await import(pathToFileURL(path).href);
  return mod.build ? mod : mod.default;
}

export async function buildWorker({ quiet = false } = {}) {
  const esbuild = await loadEsbuild();
  const result = await esbuild.build({
    entryPoints: [entry],
    bundle: true,
    format: "iife",
    platform: "browser",
    target: "es2020",
    minify: true,
    legalComments: "none",
    write: false,
    logLevel: "silent",
  });
  const code = result.outputFiles[0].text;
  // Escape "<" so the string can never close a <script> tag when the app bundle is inlined into HTML.
  const literal = JSON.stringify(code).replace(/</g, "\\u003c").replace(/\u2028/g, "\\u2028").replace(/\u2029/g, "\\u2029");
  const module = `// GENERATED by scripts/build-worker.mjs from src/sim/worker-entry.ts. Do not edit; rebuild with \`pnpm --filter viewer build:worker\`.\n` +
    `/* eslint-disable */\n` +
    `export const WORKER_SOURCE: string = ${literal};\n`;
  const previous = existsSync(outFile) ? readFileSync(outFile, "utf8") : null;
  if (previous !== module) writeFileSync(outFile, module);
  if (!quiet) console.log(`[build-worker] ${outFile} (${(code.length / 1024).toFixed(1)} KiB${previous === module ? ", unchanged" : ""})`);
  return { code, outFile };
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  await buildWorker();
}
